### ISSUE TITLE
Decode hex to number?

### ISSUE THREAD

**Issue by thedrow** [zbjornson/fast-hex#2]
How do I convert the resulting uint8_t array to a number?

**Comment by zbjornson** [comment]
Just index into the pointer, `uint8_t value = dest[i]`.

**Comment by thedrow** [comment]
So this function decode hex numbers to integers in batches? It's not very clear from the documentation.

**Comment by zbjornson** [comment]
I'll improve the docs, but yes, it decodes char buffers into `uint8_t` buffers (and reverse for encoding). If you're just decoding a single number, you'd be better off using [`strtol`](http://en.cppreference.com/w/c/string/byte/strtol) or similar. The speed in this library comes from using vectorized operations to decode/encode multiple values at once.

**Comment by thedrow** [comment]
I'm not sure I understand the output of those functions.
Can you please provide some examples?

**Comment by zbjornson** [comment]
Something like this:

```cpp
const uint8_t* src = (uint8_t*)"262a3445";
uint8_t* dest = new uint8_t[4];
decodeHexVec(dest, src, 4);
// dest now contains {38, 42, 52, 69} i.e. {0x26, 0x2a, 0x34, 0x45}
```

**Comment by thedrow** [comment]
Oh so you take a string and convert it to hexadecimal digits (so the representation of numbers in dst is in base 16).
Why would you want to do that?
262a3445 can also be a whole hexadecimal number which is why I was confused.

**Comment by zbjornson** [comment]
Hex encodes 4 bits per character. 0x262a3445 can be decoded by `reinterpret_cast<uint32_t>`'ing the buffer.
