### ISSUE TITLE
encodeHexVec result is error

### ISSUE THREAD

**Issue by lyjdgkg** [zbjornson/fast-hex#4]
bin = {128,0,48,192,47,52,0,0,0,0,0,0,0,0,0,0,0,0,0,08,0,0,0,156 ，
1,0,0,140,​​2,0,0,0,0,0,0,0,0,32,0,00,96,46,99 } 
result = 8f0030cf2f340000000000000000000000000000300000009f0100008f0200000000000005000000200050602e63
encodeHexVec result is error
Correct is = 800030c02f340000000000000000000000000000300000009c0100008c0200000000000005000000200050602e63

**Comment by zbjornson** [comment]
Oops, good catch, confirmed. Will fix later today and add tests.

**Comment by lyjdgkg** [comment]
I am through translation, the expression may not be accurate
decodeHexVec also has bugs, I made changes to be normal. Otherwise decodeHexBMI will overflow write


void decodeHexVec(uint8_t* __restrict__ dest, const uint8_t* __restrict__ src, size_t len) {
	const __m256i A_MASK = _mm256_setr_epi8(
		0, -1, 2, -1, 4, -1, 6, -1, 8, -1, 10, -1, 12, -1, 14, -1,
		0, -1, 2, -1, 4, -1, 6, -1, 8, -1, 10, -1, 12, -1, 14, -1);
	const __m256i B_MASK = _mm256_setr_epi8(
		1, -1, 3, -1, 5, -1, 7, -1, 9, -1, 11, -1, 13, -1, 15, -1,
		1, -1, 3, -1, 5, -1, 7, -1, 9, -1, 11, -1, 13, -1, 15, -1);

	const __m256i* val3 = reinterpret_cast<const __m256i*>(src);
	__m256i* dec256 = reinterpret_cast<__m256i*>(dest);

	while (len >= 64) {
		__m256i av1 = _mm256_lddqu_si256(val3++); // 32 nibbles, 16 bytes
		__m256i av2 = _mm256_lddqu_si256(val3++);
		// Separate high and low nibbles and extend into 16-bit elements
		__m256i a1 = _mm256_shuffle_epi8(av1, A_MASK);
		__m256i b1 = _mm256_shuffle_epi8(av1, B_MASK);
		__m256i a2 = _mm256_shuffle_epi8(av2, A_MASK);
		__m256i b2 = _mm256_shuffle_epi8(av2, B_MASK);

		// Convert ASCII values to nibbles
		a1 = unhexBitManip(a1);
		a2 = unhexBitManip(a2);
		b1 = unhexBitManip(b1);
		b2 = unhexBitManip(b2);

		// Nibbles to bytes
		__m256i bytes = nib2byte(a1, b1, a2, b2);

		_mm256_store_si256(dec256++, bytes); // Warning: change to storeu if dest is not aligned
		len -= 64;
	}
	dest = (uint8_t*)dec256;
	src = (uint8_t*)val3;
	decodeHexBMI(dest, src, len >> 1);
}

**Comment by lyjdgkg** [comment]
I am through translation, the expression may not be accurate
decodeHexVec also has bugs, I made changes to be normal. Otherwise decodeHexBMI will overflow write

void decodeHexVec(uint8_t* __restrict__ dest, const uint8_t* __restrict__ src, size_t len) {
	const __m256i A_MASK = _mm256_setr_epi8(
		0, -1, 2, -1, 4, -1, 6, -1, 8, -1, 10, -1, 12, -1, 14, -1,
		0, -1, 2, -1, 4, -1, 6, -1, 8, -1, 10, -1, 12, -1, 14, -1);
	const __m256i B_MASK = _mm256_setr_epi8(
		1, -1, 3, -1, 5, -1, 7, -1, 9, -1, 11, -1, 13, -1, 15, -1,
		1, -1, 3, -1, 5, -1, 7, -1, 9, -1, 11, -1, 13, -1, 15, -1);

	const __m256i* val3 = reinterpret_cast<const __m256i*>(src);
	__m256i* dec256 = reinterpret_cast<__m256i*>(dest);

	while (len >= 64) {
		__m256i av1 = _mm256_lddqu_si256(val3++); // 32 nibbles, 16 bytes
		__m256i av2 = _mm256_lddqu_si256(val3++);
		// Separate high and low nibbles and extend into 16-bit elements
		__m256i a1 = _mm256_shuffle_epi8(av1, A_MASK);
		__m256i b1 = _mm256_shuffle_epi8(av1, B_MASK);
		__m256i a2 = _mm256_shuffle_epi8(av2, A_MASK);
		__m256i b2 = _mm256_shuffle_epi8(av2, B_MASK);

		// Convert ASCII values to nibbles
		a1 = unhexBitManip(a1);
		a2 = unhexBitManip(a2);
		b1 = unhexBitManip(b1);
		b2 = unhexBitManip(b2);

		// Nibbles to bytes
		__m256i bytes = nib2byte(a1, b1, a2, b2);

		_mm256_store_si256(dec256++, bytes); // Warning: change to storeu if dest is not aligned
		len -= 64;
	}
	dest = (uint8_t*)dec256;
	src = (uint8_t*)val3;
	decodeHexBMI(dest, src, len >> 1);
}

**Comment by lyjdgkg** [comment]
> Oops, good catch, confirmed. Will fix later today and add tests.

I am through translation, the expression may not be accurate
decodeHexVec also has bugs, I made changes to be normal. Otherwise decodeHexBMI will overflow write

```cpp
void decodeHexVec(uint8_t* __restrict__ dest, const uint8_t* __restrict__ src, size_t len) {
	const __m256i A_MASK = _mm256_setr_epi8(
		0, -1, 2, -1, 4, -1, 6, -1, 8, -1, 10, -1, 12, -1, 14, -1,
		0, -1, 2, -1, 4, -1, 6, -1, 8, -1, 10, -1, 12, -1, 14, -1);
	const __m256i B_MASK = _mm256_setr_epi8(
		1, -1, 3, -1, 5, -1, 7, -1, 9, -1, 11, -1, 13, -1, 15, -1,
		1, -1, 3, -1, 5, -1, 7, -1, 9, -1, 11, -1, 13, -1, 15, -1);

	const __m256i* val3 = reinterpret_cast<const __m256i*>(src);
	__m256i* dec256 = reinterpret_cast<__m256i*>(dest);

	while (len >= 64) {
		__m256i av1 = _mm256_lddqu_si256(val3++); // 32 nibbles, 16 bytes
		__m256i av2 = _mm256_lddqu_si256(val3++);
		// Separate high and low nibbles and extend into 16-bit elements
		__m256i a1 = _mm256_shuffle_epi8(av1, A_MASK);
		__m256i b1 = _mm256_shuffle_epi8(av1, B_MASK);
		__m256i a2 = _mm256_shuffle_epi8(av2, A_MASK);
		__m256i b2 = _mm256_shuffle_epi8(av2, B_MASK);

		// Convert ASCII values to nibbles
		a1 = unhexBitManip(a1);
		a2 = unhexBitManip(a2);
		b1 = unhexBitManip(b1);
		b2 = unhexBitManip(b2);

		// Nibbles to bytes
		__m256i bytes = nib2byte(a1, b1, a2, b2);

		_mm256_store_si256(dec256++, bytes); // Warning: change to storeu if dest is not aligned
		len -= 64;
	}
	dest = (uint8_t*)dec256;
	src = (uint8_t*)val3;
	decodeHexBMI(dest, src, len >> 1);
}
```

(edited to fix code formatting)

**Comment by zbjornson** [comment]
I just pushed the fix for `encodeHexVec` but haven't added tests yet.

Looking at `decodeHexVec` now.

**Comment by zbjornson** [comment]
@lyjdgkg I just pushed a commit that clarifies the `len` parameter and cleaned up the way indexing is done. For `decodeHexVec()`, `len` is the number of bytes in the output buffer (half the size of the input buffer), not the input buffer. Is that what you were using?

**Comment by lyjdgkg** [comment]
@zbjornson The len of decodeHexBMI should also have a note

**Comment by zbjornson** [comment]
Just pushed some more cleanup. Let me know if anything is unclear or if you find any other issues please. Thanks!
